In [1]:
import pandas as pd

In [2]:
#business
df_en = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\business\english_ds_business.txt', delimiter = "\t", header=None, names=['en'])
df_zh = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\business\chinese_ds_business.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh = pd.concat([df_en, df_zh], axis=1)

#latest
df_en1 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\latest\english_ds_latest.txt', delimiter = "\t", header=None, names=['en'])
df_zh1 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\latest\chinese_ds_latest.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh1 = pd.concat([df_en1, df_zh1], axis=1)

#ent
df_en2 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\ent\english_ds_ent.txt', delimiter = "\t", header=None, names=['en'])
df_zh2 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\ent\chinese_ds_ent.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh2 = pd.concat([df_en2, df_zh2], axis=1)

#health
df_en3 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\health\english_ds_health.txt', delimiter = "\t", header=None, names=['en'])
df_zh3 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\health\chinese_ds_health.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh3 = pd.concat([df_en3, df_zh3], axis=1)

#oddities
df_en4 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\oddities\english_ds_oddities.txt', delimiter = "\t", header=None, names=['en'])
df_zh4 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\oddities\chinese_ds_oddities.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh4 = pd.concat([df_en4, df_zh4], axis=1)

#opinion
df_en5 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\opinion\english_ds_opinion.txt', delimiter = "\t", header=None, names=['en'])
df_zh5 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\opinion\chinese_ds_opinion.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh5 = pd.concat([df_en5, df_zh5], axis=1)

#politics
df_en6 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\politics\english_ds_politics.txt', delimiter = "\t", header=None, names=['en'])
df_zh6 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\politics\chinese_ds_politics.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh6 = pd.concat([df_en6, df_zh6], axis=1)

#society
df_en7 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\society\english_ds_society.txt', delimiter = "\t", header=None, names=['en'])
df_zh7 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\society\chinese_ds_society.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh7 = pd.concat([df_en7, df_zh7], axis=1)

#sports
df_en8 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\sports\english_ds_sports.txt', delimiter = "\t", header=None, names=['en'])
df_zh8 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\sports\chinese_ds_sports.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh8 = pd.concat([df_en8, df_zh8], axis=1)

#taiwan
df_en9 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\taiwan\english_ds_taiwan.txt', delimiter = "\t", header=None, names=['en'])
df_zh9 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\taiwan\chinese_ds_taiwan.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh9 = pd.concat([df_en9, df_zh9], axis=1)

#tech
df_en10 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\tech\english_ds_tech.txt', delimiter = "\t", header=None, names=['en'])
df_zh10 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\tech\chinese_ds_tech.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh10 = pd.concat([df_en10, df_zh10], axis=1)

#travel
df_en11 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\travel\english_ds_travel.txt', delimiter = "\t", header=None, names=['en'])
df_zh11 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\travel\chinese_ds_travel.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh11 = pd.concat([df_en11, df_zh11], axis=1)

#headline business
df_en12 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_business_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh12 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_business_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh12 = pd.concat([df_en12, df_zh12], axis=1)

#headline ent
df_en13 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_ent_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh13 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_ent_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh13 = pd.concat([df_en13, df_zh13], axis=1)

#headline health
df_en14 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_health_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh14 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_health_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh14 = pd.concat([df_en14, df_zh14], axis=1)

#headline oddities
df_en15 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_oddities_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh15 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_oddities_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh15 = pd.concat([df_en15, df_zh15], axis=1)

#headline opinion
df_en16 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_opinion_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh16 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_opinion_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh16 = pd.concat([df_en16, df_zh16], axis=1)

#headline politics
df_en17 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_politics_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh17 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_politics_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh17 = pd.concat([df_en17, df_zh17], axis=1)

#headline society
df_en18 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_society_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh18 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_society_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh18 = pd.concat([df_en18, df_zh18], axis=1)

#headline sports
df_en19 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_sports_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh19 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_sports_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh19 = pd.concat([df_en19, df_zh19], axis=1)

#headline taiwan
df_en20 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_taiwan_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh20 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_taiwan_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh20 = pd.concat([df_en20, df_zh20], axis=1)

#headline tech
df_en21 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_tech_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh21 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_tech_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh21 = pd.concat([df_en21, df_zh21], axis=1)

#headline travel
df_en22 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_travel_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh22 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_travel_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh22 = pd.concat([df_en22, df_zh22], axis=1)

#headline latest
df_en23 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_latest_en.txt', delimiter = "\t", header=None, names=['en'])
df_zh23 = pd.read_csv(r'D:\Google Drive\paper\new\Yi-Chun\Dataset\headline\headline_latest_zh.txt', delimiter = "\t", header=None, names=['zh'])
df_en_zh23 = pd.concat([df_en23, df_zh23], axis=1)

In [3]:
df_en_zh = df_en_zh.append(df_en_zh1, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh2, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh3, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh4, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh5, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh6, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh7, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh8, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh9, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh10, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh11, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh12, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh13, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh14, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh15, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh16, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh17, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh18, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh19, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh20, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh21, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh22, ignore_index=True)
df_en_zh = df_en_zh.append(df_en_zh23, ignore_index=True)
df_en_zh

,en,zh
0,TAIPEI (The China Post) – Taiwan stock market ...,台股近日多頭氣焰旺盛，且蔡政府施政調高最低薪資，近來3月失業率也創下過去19年間次低紀錄3....
1,"Contrary to all expectations, many employees h...",但即使經濟看似良好，許多人仍選擇到海外就業，寧願「外漂」也不在台灣發展。
2,Recent government statistics show that the num...,行政院主計總處去年底公告，2017年國人赴海外工作人數達73.6萬人，對此，人力銀行主管表示...
3,The difference lies in the ambiguous definitio...,除了長期駐派海外者，其實有更多人以「出差」名義往返海內外。專家表示，若統計數據將涵括這類灰色...
4,"In order to retain talents, Taiwan needs to ad...",許多人認為，低薪、投資不振，是台灣人才外流推手，赴外工作不僅薪酬較高，工作前景、與職涯舞台亦...
...,...,...
26183,Family Mart starts selling 75% rubbing alcoho...,75%防疫酒精在全家！18歲以下不得購買
26184,"Bids for snowball from 10 years ago top NT$40,...",天價雪球！eBay拍賣喊價四萬台幣
26185,Borough chief searches for community-spirited...,英籍男幫忙清垃圾 「用行動愛台灣」
26186,Keep the magic alive! Ghibli theme park to op...,還原宮崎駿動畫場景！2022日本吉卜力樂園 走進神隱少女食堂街、霍爾的移動城堡
26187,Burger King breaks the mold with new advertisi...,沒防腐劑最美味！「發霉漢堡」成另類行銷

# Filter English and Chinese Length Dataset

In [4]:
import  jieba

In [5]:
english = []
chinese = []

for i in range(0,len(df_en_zh)):
    if len(df_en_zh['en'][i].split()) > 6:
        if len(jieba.lcut(df_en_zh['zh'][i])) > 6:
            english.append(df_en_zh['en'][i])
            chinese.append(df_en_zh['zh'][i])

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\user\AppData\Local\Temp\jieba.cache
Loading model cost 0.689 seconds.
Prefix dict has been built successfully.

In [6]:
len(english), len(chinese)

(25451, 25451)

In [7]:
df_eng = pd.DataFrame(english, columns =['en'])
df_chi = pd.DataFrame(chinese, columns =['zh'])
df_en_zh2 = pd.concat([df_eng, df_chi], axis=1)
df_en_zh2

,en,zh
0,TAIPEI (The China Post) – Taiwan stock market ...,台股近日多頭氣焰旺盛，且蔡政府施政調高最低薪資，近來3月失業率也創下過去19年間次低紀錄3....
1,"Contrary to all expectations, many employees h...",但即使經濟看似良好，許多人仍選擇到海外就業，寧願「外漂」也不在台灣發展。
2,Recent government statistics show that the num...,行政院主計總處去年底公告，2017年國人赴海外工作人數達73.6萬人，對此，人力銀行主管表示...
3,The difference lies in the ambiguous definitio...,除了長期駐派海外者，其實有更多人以「出差」名義往返海內外。專家表示，若統計數據將涵括這類灰色...
4,"In order to retain talents, Taiwan needs to ad...",許多人認為，低薪、投資不振，是台灣人才外流推手，赴外工作不僅薪酬較高，工作前景、與職涯舞台亦...
...,...,...
25446,Family Mart starts selling 75% rubbing alcoho...,75%防疫酒精在全家！18歲以下不得購買
25447,"Bids for snowball from 10 years ago top NT$40,...",天價雪球！eBay拍賣喊價四萬台幣
25448,Borough chief searches for community-spirited...,英籍男幫忙清垃圾 「用行動愛台灣」
25449,Keep the magic alive! Ghibli theme park to op...,還原宮崎駿動畫場景！2022日本吉卜力樂園 走進神隱少女食堂街、霍爾的移動城堡
25450,Burger King breaks the mold with new advertisi...,沒防腐劑最美味！「發霉漢堡」成另類行銷

# Filter English and Chinese Dataset

In [8]:
from langdetect import detect

In [9]:
english = []
chinese = []

for i in range(0,len(df_en_zh2)):
#     print(i)
    if detect(df_en_zh2['en'][i]) == 'en':
        if detect(df_en_zh2['zh'][i]) == 'zh-tw':
            english.append(df_en_zh2['en'][i])
            chinese.append(df_en_zh2['zh'][i])

In [10]:
len(english), len(chinese)

(10147, 10147)

In [11]:
df_eng = pd.DataFrame(english, columns =['en'])
df_chi = pd.DataFrame(chinese, columns =['zh'])
df_en_zh3 = pd.concat([df_eng, df_chi], axis=1)
df_en_zh3

,en,zh
0,"Contrary to all expectations, many employees h...",但即使經濟看似良好，許多人仍選擇到海外就業，寧願「外漂」也不在台灣發展。
1,"In order to retain talents, Taiwan needs to ad...",許多人認為，低薪、投資不振，是台灣人才外流推手，赴外工作不僅薪酬較高，工作前景、與職涯舞台亦...
2,"Still, the Tsai administration hopes that comp...",然而政府也期望，美中貿易戰下的這波台商回流潮，能帶動青年在台之就業意願。
3,According to a survey conducted by 104 Job Ban...,104人力銀行表示，赴陸工作外漂族的平均薪資約是在台灣的1.72倍。
4,The issue is one of the complaints behind Pres...,強迫轉移美國技術同時也是美國總統川普(Donald Trump)引燃與北京的貿易戰 爭背後的...
...,...,...
10142,NPM to shorten opening hours to improve visito...,打破全年無休慣例！故宮14日起每週一休館
10143,Philippines representative in Taiwan says Taiw...,菲國駐臺代表：臺灣人未被禁止入境菲律賓
10144,Taiwanese stranded in Philippines as Manila en...,更新：臺灣人禁止入境菲律賓 150名臺籍旅客滯留菲國機場
10145,CECC won't allow mainland relatives to fly bac...,「國籍是可以選擇的，應自己承擔後果」 陳時中撤回陸配子女入境政策
10146,Keep the magic alive! Ghibli theme park to op...,還原宮崎駿動畫場景！2022日本吉卜力樂園 走進神隱少女食堂街、霍爾的移動城堡

# Remove Duplicate Sentences

In [12]:
df_en_zh3 = df_en_zh3.drop_duplicates(ignore_index=True)
len(df_en_zh3)

7092

In [13]:
df_en_zh3

,en,zh
0,"Contrary to all expectations, many employees h...",但即使經濟看似良好，許多人仍選擇到海外就業，寧願「外漂」也不在台灣發展。
1,"In order to retain talents, Taiwan needs to ad...",許多人認為，低薪、投資不振，是台灣人才外流推手，赴外工作不僅薪酬較高，工作前景、與職涯舞台亦...
2,"Still, the Tsai administration hopes that comp...",然而政府也期望，美中貿易戰下的這波台商回流潮，能帶動青年在台之就業意願。
3,According to a survey conducted by 104 Job Ban...,104人力銀行表示，赴陸工作外漂族的平均薪資約是在台灣的1.72倍。
4,The issue is one of the complaints behind Pres...,強迫轉移美國技術同時也是美國總統川普(Donald Trump)引燃與北京的貿易戰 爭背後的...
...,...,...
7087,Have you heard of 'Taiwan obsessed symptoms'?,日媒報導：日人罹患為珍珠而活的「台灣症」原來是因為
7088,Exploring playful Paiwan settlements hidden i...,藏身山林的童話王國，串遊排灣部落輕散策
7089,Foreigners without Taiwan NHI card can still g...,僑生持居留證、護照也能買口罩！外國人來台觀光則需自備
7090,CECC won't allow mainland relatives to fly bac...,「國籍是可以選擇的，應自己承擔後果」 陳時中撤回陸配子女入境政策
7091,Keep the magic alive! Ghibli theme park to op...,還原宮崎駿動畫場景！2022日本吉卜力樂園 走進神隱少女食堂街、霍爾的移動城堡

# source length < 1.3 * target length

In [14]:
english = []
chinese = []

#source: english, target: chinese
for i in range(0,len(df_en_zh3)):
    source_length = len(df_en_zh3['en'][i].split())
    target_length = len(jieba.lcut(df_en_zh3['zh'][i]))
    if source_length < 1.3 * target_length:
        english.append(df_en_zh3['en'][i])
        chinese.append(df_en_zh3['zh'][i])

In [15]:
len(english), len(chinese)

(6489, 6489)

In [16]:
df_eng = pd.DataFrame(english, columns =['en'])
df_chi = pd.DataFrame(chinese, columns =['zh'])
df_en_zh4 = pd.concat([df_eng, df_chi], axis=1)
df_en_zh4

,en,zh
0,"Contrary to all expectations, many employees h...",但即使經濟看似良好，許多人仍選擇到海外就業，寧願「外漂」也不在台灣發展。
1,"Still, the Tsai administration hopes that comp...",然而政府也期望，美中貿易戰下的這波台商回流潮，能帶動青年在台之就業意願。
2,According to a survey conducted by 104 Job Ban...,104人力銀行表示，赴陸工作外漂族的平均薪資約是在台灣的1.72倍。
3,The issue is one of the complaints behind Pres...,強迫轉移美國技術同時也是美國總統川普(Donald Trump)引燃與北京的貿易戰 爭背後的...
4,"In February 2018, the company announced the cl...",英國名廚傑米奧利佛於 2008 年在牛津開設了他的第一家連鎖餐廳。2018 年 2 月， 為...
...,...,...
6484,Have you heard of 'Taiwan obsessed symptoms'?,日媒報導：日人罹患為珍珠而活的「台灣症」原來是因為
6485,Exploring playful Paiwan settlements hidden i...,藏身山林的童話王國，串遊排灣部落輕散策
6486,Foreigners without Taiwan NHI card can still g...,僑生持居留證、護照也能買口罩！外國人來台觀光則需自備
6487,CECC won't allow mainland relatives to fly bac...,「國籍是可以選擇的，應自己承擔後果」 陳時中撤回陸配子女入境政策
6488,Keep the magic alive! Ghibli theme park to op...,還原宮崎駿動畫場景！2022日本吉卜力樂園 走進神隱少女食堂街、霍爾的移動城堡